### ISSUE TITLE
Multiple sites using the same storage account

### ISSUE THREAD

**Issue by jaykay-design** [sjkp/letsencrypt-siteextension#102]
Are there any known limitations with this extension when using the same storage account for multiple WebApps where all these WebApps have LetsEncrypot certificates installed?

All WebApps use the same ResourceGroup.

**Comment by sjkp** [comment]
Yes it is not a limitation of the site extension, but [timertriggered](https://github.com/Azure/azure-webjobs-sdk-extensions/wiki/TimerTrigger) web jobs (which the extension uses) will use a storage account for locking, to ensure the web job doesnt run on more than one instance. And if you are using the same storage account for multiple instances, you might not get your certificates renewed, because the web jobs are named the same in all web sites.

**Comment by jaykay-design** [comment]
Is there nay way around this? 
I have a setup where multiple WebApps use the same storage account for messaging to a web job. All these WebApps use this extension and some, as you mention correctly don't have their certificate renewed.

**Comment by sjkp** [comment]
I might be possible for me to do a change to the web job to manually override its id, that will fix the issue. I will update this issues when I have looked into it,

**Comment by sjkp** [comment]
@jaykay-design thanks for the pull request. There are some rules regarding to the hostid, you can read about it here (https://github.com/Azure/azure-webjobs-sdk/blob/master/src/Microsoft.Azure.WebJobs.Host/Executors/HostIdValidator.cs), so I changed that. I don't have a reliable way to test the fix, so please let me know if it doesnt work.

**Comment by jaykay-design** [comment]
@sjkp I've installed the new version and can confirm they are all trigger separately and the firstrun.job file is created/updated/processed correctly. Once I see all web apps renew their certificate I can confirm this issue/feature is closed for me.

**Comment by RIKIKU** [comment]
Thank you for this! This has been what was wrong with my sites for ages! The certificate renewals are working for me now.
