### ISSUE TITLE
Question: Renewal cleanup - What happens to old cert?

### ISSUE THREAD

**Issue by ai-fwd** [sjkp/letsencrypt-siteextension#114]
If possible, can you confirm that when a certificate is renewed (i.e. it generates a new cert, installs it, and updates the binding) that the old cert should be deleted? Currently i'm seeing the old cert hanging around. 

If this is not something that it currently does can i request it be added?

**Comment by sjkp** [comment]
Hi @ai-fwd 

Currently the site-extension is a messy roommate, it doesn't cleanup after itself. But it is a fair request, will added in a future version.

**Comment by RIKIKU** [comment]
@ai-fwd @sjkp If I knew how to write C# I'd help out by writing this functionality because I've seen this requested here before. All I have are these powershell skills so I wrote a script that will help out with this issue in the meantime.  It ain't pretty but it works.
http://kyledoestech.com/delete-expired-ssl-tls-webapp-certificates-in-azurerm-with-powershell/
