### ISSUE TITLE
The Lets Encrypt ACME server was probably unable to reach /.well-known/acme-challenge

### ISSUE THREAD

**Issue by getheclick** [sjkp/letsencrypt-siteextension#116]
Hi,

I just followed the this [guide](https://github.com/sjkp/letsencrypt-siteextension/wiki/How-to-install) to install the Let's Encrypt SSL certificate but in the last step it fails because can't reach /.well-known/acme-challenge/.

I've tried several things, e.g. set letsencrypt:DisableWebConfigUpdate to true or install a nuget Letsencrypt.Owin in my C# web project but nothings works.

Can you help me, please? I'm running the web on a Azure Cloud Service, and I have an Azure SQL server instance and a Blob container (I don't know if this information is helpful, but here you have).

Thanks in advance,
Daniel

**Comment by sjkp** [comment]
The extension is for azure web apps only (and functions because that is also hosted on web apps). It doesn't support cloud services.

**Comment by getheclick** [comment]
Thanks for the information, I didn't know the extension is just supported for web apps. 

So I suppose that if I'm using Azure Cloud Service, the only way to configure Let's Encrypt SSL is following this article:  https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-configure-ssl-certificate-portal   

There is no easy way (site extension) to do it, right?

Best regards,
Daniel

**Comment by luisgizirian** [comment]
Daniel, certainly there's no easy way.

You may try on automating over a web role.

Also, if enough budget for additional VM,  seting up an additional NVA with
Nginx is an option. There, you can automate Let's Encrypt Cert setup and
renewal (https://www.bjornjohansen.no/letsencrypt-nginx), offloading
encryption/decryption into the NVA, so the web role(s) behind don't have to
bother (nor be setup with a certificate, which is the sole point here).

Double quote the latter paragraph, cause it's hand-tied on the apps
architecture and specifics (perhaps the app needs to handle SSL at some
level, which is still possible, but you'll be back right at the
web-role/certificate issue).

There's a lot to digest here as there're other aspects such as High
Availability for your Roles and NVAs as well, that could complicate things
even more.

Back to original question, I'm not sure if there's anyone who's managed to
automate LE Cert setup and renewal for Roles uncomplicated scenarios.

IaaS has gas enough for some more miles, so if our good friend @sjkp has
some spare time to get his head around it, would be fantastic.

Cheers!
Luis


On Wed, Mar 29, 2017 at 4:40 AM getheClick <notifications@github.com> wrote:

Thanks for the information, I didn't know the extension is just supported
for web apps.

So I suppose that if I'm using Azure Cloud Service, the only way to
configure Let's Encrypt SSL is following this article:
https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-configure-ssl-certificate-portal

There is no easy way (site extension) to do it, right?

Best regards,
Daniel

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sjkp/letsencrypt-siteextension/issues/116#issuecomment-290009120>,
or mute the thread

**Comment by sjkp** [comment]
It is not something that is in my interest to build, as I see cloud services as an old technology, that I'm personally have no plan on using in new solutions. 

Also building a automated solution for cloud services and lets encrypt certificates, is going to be quite a challenge. 

The main problem is that the certificate information is part of the deploy package, so basically the certificate has to be obtained at build time. That is doable, by using the letsencrypt dns challenge, and some good build scripts. The next challenge is then to auto update the certificate once they are installed, that could be handled by a timer job running somewhere that can create start new deployments. The timer job either have to have access to the DNS server used for the domain to update the TXT record, or have remote access to all web roles, to place the new http challenge files. Both solutions are ugly to me. 

All in all, it is hard to make a one-size fits all solutions for cloud services, which is why I don't want to invest time in it (and probably also why noone else have).

**Comment by luisgizirian** [comment]
Thanks for your detailed answer @sjkp! Completely valid points you're
making. Luis.

**Comment by getheclick** [comment]
Thanks for your responses. 

Actually I was using initially an Azure Webapp but the project needed Crystal Reports to generate reports in pdf, so we moved the solution into a Azure Cloud Service to be able to install the Crystal Reports in the server (it's a pain because each publish you upload the whole bin file and it takes too long time). 

So after this issue with the SSL certificate, I think the best solution is to move again into an Azure Webapp and search an alternative for the reporting which do not need to upload  83MB each time, maybe one of this two nugets (I'll have to test if they work):
- [Report.NET PDF Generator](https://github.com/ritchiecarroll/Report.NET)
- [DoddleReport](https://github.com/matthidinger/DoddleReport)

Thanks all of you for your help. 
Best regards,
Daniel

**Comment by sjkp** [comment]
@getheclick I would advice you to do some quick test in a web app of the pdf component you are planning to use, because many pdf components rely on GDI which is not supported in web apps. It is kinda annoying, but the sandbox that web apps run in have this limitation. In most cases it means you have to run your pdf component in either cloud service or a VM. 

https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#user-content-win32ksys-user32gdi32-restrictions
