### ISSUE TITLE
When creating a certificate over the Semi Automated UI, 2 certificates are created

### ISSUE THREAD

**Issue by alexmaie** [sjkp/letsencrypt-siteextension#128]
Hey,

First of all, thanks for all the effort that was put into this extension :).

Looks like there is a bug with the latest version. Everytime I use the UI to create a certificate, two certificates are created for the requested domain. If I can help with diagnostics, please let me know

Example image. Domain that starts with patientportal has 2 certificates

![image](https://cloud.githubusercontent.com/assets/4498593/25232752/2dfbf63c-25e5-11e7-9a1b-6bc8da9650e8.png)

**Comment by sjkp** [comment]
@alexmaie thanks for reporting this. I will check what is going on.

**Comment by sjkp** [comment]
As far as I can see from your screenshot, the certificates are not requested at the same time. So doubt that it happend the way you think. 

Could it be that you have everything in place in the app settings variables `letsencrypt:....` before you wen to the UI? Because if you have configured everything in the app settings before hand, the web job will automatically install install the certificate, so in that case you don't have to use the UI.

**Comment by alexmaie** [comment]
Yes,

I have everything preconfigured because initially, So, If I install the
extension, and everything is configured, then the webjob kicks in and
configured the certificate?

**Comment by sjkp** [comment]
Yes that is the intention, so that unattended setups are possible. 

I will consider the issue resolved then, please post if you disagree.
