### ISSUE TITLE
'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...)

### ISSUE THREAD

**Issue by JamesReate** [sjkp/letsencrypt-siteextension#14]
When configuring for the first time, ie. setting Tenant, Subscription, ClientId etc, and hit next, keep getting this error:

```
'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...)
Parameter name: authority
```

![image](https://cloud.githubusercontent.com/assets/2886324/12631918/4e1e3e0e-c522-11e5-8133-2ee50d523927.png)

**Comment by TWith2Sugars** [comment]
I had this problem as well, you need the ApplicationSettings set up first: ![](https://msgimages.blob.core.windows.net/images/f57d6e59-0a6b-44d4-8e4d-a4564eb8d8d1.png)

**Comment by sjkp** [comment]
@JamesReate as @TWith2Sugars mentions you have to setup the proper app setting first. That is also what the text on the first page in the site-extension tries to tell you. 
I will in the next version add some more validation to avoid this problem. 
The reason for the settings to be in your appsettings, are so they are available for the web job, so it can renew the certificate, otherwise you would have to manually renew the certificate, which is not the purpose of letsencrypt certificates.

**Comment by sjkp** [comment]
A side note, I could just let you add the settings from the site extensions, but I like to avoid that as it would restart your site.

**Comment by JamesReate** [comment]
Ahh, I see, I thought that part was optional or would get added automagically from the config screen.
