### ISSUE TITLE
Automated Installation ended up with a staging cert.

### ISSUE THREAD

**Issue by smil2k** [sjkp/letsencrypt-siteextension#173]
# Environment

Using LE site extension with Azure Functions. I was working great with the manual setup. 
I though that I don't need to do anything in order to get automatic setup of new certificates. 
Clearly I missed the "automated installation" part in the setup, so non of the properties mentioned was given. 

The last run did detect the situation and requested a new staging certificate!

# Expected result

This was a bit surprising, because I would have expected that without mentioning the acme host, that the background process would not run at all. (or using the prod server) 

Anyhow, I've configured the values now, let's see next week what will happen :-)

**Comment by sjkp** [comment]
This is an unfortunate side effect of the letsencrypt staging environment being the default environment for the extension. The reason why I opted for the staging as the default, is that unlimited certificates can be requested from the staging environment, so it seemed better if people where playing around. 

The reason why you ended up with a staging certificate, is probably because the `D:\home\data\letsencrypt\settings.json` got deleted. This file contains the settings as they were saved after the initial manual setup, and the web job uses it, if no app settings are present for the `letsencrypt:AcmeBaseUri` key. 

To avoid something similar happening in the future I recommend relying only on apps settings, which means you would have to manually add the following two app settings:

key | value
-- | --
letsencrypt:AcmeBaseUri | The url to Let's Encrypt servers e.g. https://acme-v01.api.letsencrypt.org/ or https://acme-staging.api.letsencrypt.org/ (defaults to this)
letsencrypt:Email | The Email used for registering with Let's Encrypt

**Comment by smil2k** [comment]
Hi,

It is possible that the settings.json is only used for manual setup? I did not created this file, but there is one currently. 
(Additionally my last request was a prod cert, so I would have expected that this would be the case.)

**Comment by sjkp** [comment]
Which Url does your settings.json contain it should have: 
`
{"Name":"baseUri","Value":"https://acme-v01.api.letsencrypt.org/","Count":0}
`
if it is going to hit production LE servers.

**Comment by smil2k** [comment]
I see. 

This is my settings.json:

[{"Name":"email","Value":"xxx@yyy.zz","Count":0},{"Name":"baseUri","Value":"https://acme-staging.api.letsencrypt.org/","Count":0},{"Name":"email","Value":"xxx@yyy.zz","Count":0},{"Name":"baseUri","Value":"https://acme-staging.api.letsencrypt.org/","Count":0},{"Name":"email","Value":"xxx@yyy.zz","Count":0},{"Name":"baseUri","Value":"https://acme-v01.api.letsencrypt.org/","Count":0},{"Name":"email","Value":"xxx@yyy.zz","Count":0},{"Name":"baseUri","Value":"https://acme-v01.api.letsencrypt.org/","Count":0}]

As you see, all manual executions adds another set of entries, not overwriting. Additionally it seems the reader skip duplicates. 

This way the background job uses the first setting always instead of the last. I think the latter would be a better option. (if not using the file is not an option.) This way there would be no surprise. Additionally the app settings would be redundant.

**Comment by sjkp** [comment]
THe app setting take precedence, and it does so, because you can actually use the extension without ever going through the manual process. 

However, it was unintended that it saves multiple values to the settings.json file. So I will fix that.

**Comment by sjkp** [comment]
Should be fixed in 0.8.5.
