### ISSUE TITLE
WebJob has disappeared with no changes to app

### ISSUE THREAD

**Issue by koldskool** [sjkp/letsencrypt-siteextension#178]
I don't know if this is a real issue or user error - I've been through the other issues and haven't found an answer. I have 2 slightly different scenarios - 

In one the letsencrypt64 web job has disappeared with no changes to the Azure app service (other than updates to static files and a restart) and the certificate has therefore not renewed.

In the other the letsencrypt64 web job has disappeared after a new version of the web app was applied that uses its own web jobs - again the certificate has not renewed (predictably).

In both cases the extension is still installed (x64, version 0.6.17) and a manual trigger of it updates the certificates successfully. My question is, have I done anything wrong or have I overlooked a step? For the app with its own web jobs, do I need to adjust its configuration to make it possible to run letsencrypt alongside it? Or should I take a step back/sideways and use the NuGet prerelease version to integrate with my own code?

**Comment by ohadschn** [comment]
Could this be your issue? https://github.com/sjkp/letsencrypt-siteextension/issues/22

**Comment by koldskool** [comment]
Thanks for the reply. That option is normally set to "off" i.e. Do not remove additional files but it is possible that one or more publications did have it turned back on. I'll double check, but in that case is there a workaround to resurrect the jobs without a full un/re-install?

**Comment by ohadschn** [comment]
This is just a guess, but I assume you could manually build and upload the WebJob yourself:
https://github.com/sjkp/letsencrypt-siteextension/tree/master/LetsEncrypt.SiteExtension.WebJob. I'd wait for Simon to chime in though.

I also created a standalone WebJob based on this extension's logic (specifically to avoid this issue), that you might want to check out: https://github.com/ohadschn/letsencrypt-webapp-renewer

**Comment by sjkp** [comment]
I would recommend that you just reinstall the latest version, you dont need the specific x64 bit version anymore. 

There is not much harm in reinstalling the extension, most settings are stored in the web.config and will not be removed when you uninstall. And the few things you manually choose during the first installation are also saved outside of the directory of the extension itself, so they should also be there after a reinstall. 

To the question, I can't say what removed the web job. I shouldn't remove itself, so the best guess is that somehow you accidentally published it with remove additional files. If that happens, you can just remove and reinstall as mentioned earlier, and you should be good, it is not the end of the world (well unless you dont notice). 

But even if you don't notice you should get a warning mail from letsencrypt 20 days before the certificate expires that it hasn't been renewed, you should act on this mail, because that means the extension failed to do its job.

**Comment by sjkp** [comment]
Btw reinstall is not a thing in the UI, so you just have to uninstall it and the install it again :)

**Comment by koldskool** [comment]
Thanks for the help. Uninstall and re-install seems to have resurrected the webjobs (and not deleted **my** webjobs) so I guess it must have just been a publishing error. I'm making sure all my co-workers are aware so that doesn't happen again.
