### ISSUE TITLE
Unsupported Protocol

### ISSUE THREAD

**Issue by cdeli** [sjkp/letsencrypt-siteextension#179]
Have a Wordpress Site in Azure that I added the SSL cert to from letsencrypt. Everything went well, when I try and navigate to the site I get the following:

This site can’t provide a secure connection

kta-training.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
HIDE DETAILS
Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.

I am using the latest chrome version, 62.0.3202.94

in Edge I get this

Can’t connect securely to this page
This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.

Any idea on what to do here?

**Comment by sjkp** [comment]
It looks fine to me: https://www.ssllabs.com/ssltest/analyze.html?d=kta-training.com 

If you want it to work on the non-naked domain, e.i. on https://www.kta-training.com you have to include that subdomain in your request when you order the certificate. Which you do by multi selecting the hostnames, before you click request and install certificates.

**Comment by cdeli** [comment]
Huh... interesting, I couldn't even navigate to it last night. I am able to now just fine.

Issue is that the cert, though showing that it is secure, does not seem to be reading the cert properly. When you navigate to it, the site still reads as insecure even though the certs are applied.

**Comment by sjkp** [comment]
The page have mixed content not everything is served over https, which is why you dont get the pad lock, if that is how you check if the site is secure. 

Specifically:
http://kta-training.com/wp-content/uploads/2017/06/KTA_1000x500-e1496436118609.png 
http://kta-training.com/wp-content/uploads/2016/02/bg_sub-header_2.png?id=211 

I will close this issue, as it is not related to the extension, probably a wordpress thing, or just some hardcoded URLs.
