### ISSUE TITLE
intermittent invalid security certificate

### ISSUE THREAD

**Issue by 0xNF** [sjkp/letsencrypt-siteextension#202]
About one in every 4 page loads, the cert loaded for a given Azure hosted page issued with the site extension loads as an invalid cert. Specifically it complains about the domains *.azurewebsites.net, *.scm.azurewebsites.net, *.azure-mobile.net, *.scm.azure-mobile.net, and *.sso.azurewebsites.net 

![image](https://user-images.githubusercontent.com/1915007/36948199-e98d111a-1f8b-11e8-9209-535518c269d9.png)

This is an intermittent problem - most page loads produce a certificate that is correctly assigned for the domain. Is there an existing issue along these lines, or is there any advice on how to remedy this?

**Comment by bocktar** [comment]
Be sure that the DNS for your custom domain is pointed to the right IP address. 

I had this situation pop up before, and it turned out that changes by Microsoft caused the address to change for a site to which I had made no modifications for months. The old ones still intermittently worked, and it made it really difficult to troubleshoot.

**Comment by 0xNF** [comment]
Thanks for the fast response. 

It didn't occur to me that I would be issued multiple IP addresses on an azure host.
Setting A Records for each of the IP's found under the Azure Portal's Outbound IP addresses section seems to have resolved it.
