### ISSUE TITLE
possible issue with deployment slots

### ISSUE THREAD

**Issue by mrbasil** [sjkp/letsencrypt-siteextension#21]
I can't seem to use the extension with this setup.

app service name: xxx
production slot (unnamed): 
   custom domain name: xxx.company.com
uat slot (name = uat)
   custom domain name: xxx-uat.company.com

production slot works okay as the WEBSITE_SITE_NAME = xxx, so it pulls the correct custom domain name (xxx.company.com).

however, the uat slot has WEBSITE_SITE_NAME = xxx as well, so it's incorrectly pulling custom domain name xxx.company.com instead of xxx-uat.company.com

Did I miss something in the config?

**Comment by mbasil77** [comment]
I'm not sure how big of a deal this is (for me) ... I'm going to re-structure to avoid using the deployment slots and opt for a flatter structure.

**Comment by sjkp** [comment]
I haven't tested it with deployment slots. I will look into it. 

Personally I don't use them though. I rather have separate environment, but think I should be able to make it work.

**Comment by mbasil77** [comment]
After looking at this more I tend to agree ... I'm breaking out the environments more cleanly now.

That said ... if you need or want someone to test out the deployment configuration I'll do it.

**Comment by danww** [comment]
I'd be keen for this to work in deployment slots, too.
We've worked around this by breaking out into separate web apps, but it would be good if it could work in slots.

**Comment by stuartleeks** [comment]
It would be great to have this working in site slots! I just spent a bunch of time checking the service principal, deleting and recreating, etc. I finally checked and spotted that the settings hadn't been written, and when I realised that they were set on the main slot I came back to search here.

I got the error below because the settings had been written to the production slot, not the slot that the  extension was installed in. The error message included to help people find this issue if they hit the problem :-)

    'authority' Uri should have at least one segment in the path (i.e. https://<host>/<path>/...)
    Parameter name: authority
