### ISSUE TITLE
Certificate was not found

### ISSUE THREAD

**Issue by jsayce** [sjkp/letsencrypt-siteextension#23]
I followed Nik Molnar's instructions, and everything seemed fine until the final step: requesting and installing the certificate. This give the error and stack trace shown below.

The Azure portal doesn't show the new certificate, but if I run the site extension again then the certificate is shown in the list at the bottom of the /Home/Hostname page.

I've checked in /SiteExtensions/letsencrypt/config/httpsacme-v01.api.letsencrypt.org and in both the staging and production folders there are the 11 files you mention on [Issue 18](https://github.com/sjkp/letsencrypt-siteextension/issues/18#issuecomment-180720624).

This looks similar to [Issue #9](https://github.com/sjkp/letsencrypt-siteextension/issues/9) - is there a problem with having everything in one resource group?

```
Server Error in '/letsencrypt' Application.

Certificate 4F0D6A15CAAE0FAEAECADE6C7866CE118DE6A8DC was not found.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: Microsoft.Rest.Azure.CloudException: Certificate 4F0D6A15CAAE0FAEAECADE6C7866CE118DE6A8DC was not found.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[CloudException: Certificate 4F0D6A15CAAE0FAEAECADE6C7866CE118DE6A8DC was not found.]
   Microsoft.Azure.Management.WebSites.<BeginCreateOrUpdateSiteWithHttpMessagesAsync>d__31.MoveNext() +5977
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13847892
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Azure.Management.WebSites.<BeginCreateOrUpdateSiteAsync>d__53.MoveNext() +408
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13847892
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
   Microsoft.Azure.Management.WebSites.SitesOperationsExtensions.BeginCreateOrUpdateSite(ISitesOperations operations, String resourceGroupName, String name, Site siteEnvelope, String skipDnsRegistration, String skipCustomDomainVerification, String forceDnsRegistration, String ttlInSeconds) +306
   LetsEncrypt.SiteExtension.Core.CertificateManager.Install(Target target, String pfxFilename, X509Certificate2 certificate) in C:\Projects\LetsEncrypt-SiteExtension\LetsEncrypt-SiteExtension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:488
   LetsEncrypt.SiteExtension.Core.CertificateManager.Auto(Target binding) in C:\Projects\LetsEncrypt-SiteExtension\LetsEncrypt-SiteExtension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:444
   LetsEncrypt.SiteExtension.Core.CertificateManager.RequestAndInstallInternal(Target target) in C:\Projects\LetsEncrypt-SiteExtension\LetsEncrypt-SiteExtension\LetsEncrypt.SiteExtension.Core\CertificateManager.cs:237
   LetsEncrypt.SiteExtension.Controllers.HomeController.Install(RequestAndInstallModel model) +697
   lambda_method(Closure , ControllerBase , Object[] ) +139
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +209
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +67
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +30
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +65
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +137

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0
```

**Comment by sjkp** [comment]
It should work just fine having everything in on resource group, that is how I do it. 

Did you give the service principal access to the resource group?

**Comment by jsayce** [comment]
Hi Simon - thank for the response.

Yes, I ran this command:

`New-AzureRmRoleAssignment -RoleDefinitionName Contributor -ServicePrincipalName $app.ApplicationId`

If I check the user access to the resource group in the portal then it shows the service principal has the contributor role, so I think that worked ok.

**Comment by sjkp** [comment]
I just tried testing it again. I can't reproduce the error. Can you see the certificate if you just use the blade in the portal? 
![image](https://cloud.githubusercontent.com/assets/3397744/13266142/e57ed6e6-da76-11e5-9a44-446c1b431300.png)

I'm grasping for straws here, but i think it could be some timing issue. Because the certificate uploaded to the hosting plan, so maybe it is uploaded by not yet accessible (My code don't wait it just expects it to be immediately available). So if you can provide more info about your setup, I can maybe get to the bottom of this e.g. if you run multiple sites on the same app hosting plan

**Comment by Anheledir** [comment]
I got the same error here. The Service Principal has access to the website and to the storage, but I cannot see the certificates within the website settings (only within the settings of the extension, as mentioned by @jsayce).

The webapp is running within a S1 instance (there is only on other webapp within this instance).

**Comment by sjkp** [comment]
@Anheledir thanks for the input. How did you create the resource group and app hosting plan? From the portal? Because obviously my test setup is not good enough, I'm building my test setup from an ARM template everytime I develop on this project, and havn't experienced this.

**Comment by Anheledir** [comment]
I created the Resource-Group during creation of the Web-App. The App hosting plan was already created for another website (during the creation by the portal-wizard, too) and because of this the plan is in another resource group. The service principal got permissions for both of them.

If it may help you I can install a debug version on my setup (not yet a productive setup) to collect further details.

**Comment by sjkp** [comment]
@Anheledir thanks. I will double check that the change I did still works for solutions where service plan is in a different resource group.

**Comment by sjkp** [comment]
@Anheledir did you set ServicePlanResourceGroupName to the actual name of the resource group that holds the app hosting plan? (I can see the naming can be confusing).
![image](https://cloud.githubusercontent.com/assets/3397744/13378645/314dbab2-de0d-11e5-9d8d-bbc308931fbd.png)

Because if I use the same setup as you with seperate resource group for web app and app hosting plan, but fail to set the ServicePlanResourceGroupName to the resource group name of the app hosting plan i get the same error as you do. If set correct everything works as expected.

**Comment by Anheledir** [comment]
That fixed the problem, thank you!

**Comment by jsayce** [comment]
Brilliant - thanks @sjkp - that's fixed my problem too :-)

**Comment by stiucsib86** [comment]
I'm having this issue too. 
- ResourceGroup and ServicePlanResourceGroup are the same.
- 11 files (Signer, Registration, .pfx files) generated are in the config folder.
- Log Stream shows that the error was thrown after "Installing certificate..." 
![screen-shot-2016-05-06-at-5 19 16-pm](https://cloud.githubusercontent.com/assets/74789/15069377/c548892c-13af-11e6-893a-8346bab5388e.jpg)

What could possibly be the reason?

**Comment by sjkp** [comment]
@stiucsib86 how is your setup, is your app service plan in the same resource group as you app service? 
Only if they are in the same group should you set resourcegroup and serviceplanresourcegroup to the same. 
This error (unless it is some internal Azure problem, which I doubt), is because when installing the certificate the site extension looks in the resource group that you specified in the serviceplanresourcegroup for the certificate, that group should be the group that contains the app hosting plan, as certificates are installed on the machine running the web sites, that machine is ALWAYS in the app service plan resource group.
