### ISSUE TITLE
ClientId registered under application settings

### ISSUE THREAD

**Issue by gcliv** [sjkp/letsencrypt-siteextension#280]
Receiving the following error on following the GUI for the app services extension. All fields are populated on the form and double checked.

"The ClientId registered under application settings 00000000-0000-0000-0000-000000000000 does not match the ClientId you entered here {XXX}"

**Comment by sjkp** [comment]
You probably just need to hit the check box for updating application settings. This error shows up when the application settings of the web app is different from what you typed into the UI. 
The UI is used to update the application settings, but because that causes the site to restart, the extension doesnt automatically just update the application settings. 
The reason why it needs to be saved in the application settings, is for the information to be available for web job, so that renewal also works unattended.
