### ISSUE TITLE
Updating To ACMEv2 Question

### ISSUE THREAD

**Issue by ewwwgiddings** [sjkp/letsencrypt-siteextension#351]
I was running a version that was not using ACMEv1 and was sent an email to update.

I updated the site extension to ACMEv2 through my website's Kudu dashboard.

I clicked "Update" in the SiteExtensions section, and it updated.

My question:
Do I now need to click "Launch" (the play button) to implement the updated extension, or will it use the updated extension the next time the WebJob is run?

Thanks to anyone who can help me understand if clicking update is sufficient or if any other actions are necessary.

**Comment by khalidcawl** [comment]
According [this comment](https://github.com/sjkp/letsencrypt-siteextension/issues/343#issuecomment-553119941), the extension is now using ACMEv2 since version 1.0.1. If you have updated it, it will use the new protocol next time it requests the certificate. You don't have to do anything else. Please confirm @ohadschn

**Comment by ohadschn** [comment]
@khalidcawl I'm not the owner of this repo but yes, this is my understanding...
