### ISSUE TITLE
doesn't tie certificate to website

### ISSUE THREAD

**Issue by curelom** [sjkp/letsencrypt-siteextension#38]
Running mvc 5, followed directions from Nik Molar.  Verified .wellknown/acme-challenge is browsable. Run through the scm Let's encrypt site extension and click on request and install certificate.  Sometimes it shows certificate not found.  Other times just stops processing.  I go back to the main the page previous to the request and install certificate and I see certificates at the bottom of the page, but the list of of Hostname SSL bindings websites all show SSL state Disabled.  I don't know where to go further to debug this.  Running site extension version 0.47

**Comment by chadwackerman** [comment]
See #36 for the "just stops processing" issue. Basically this thing doesn't work at all at the moment because the Let's Encrypt servers got busier. It also doesn't provide an error response on the most common page. Developer doesn't seem to care.

**Comment by curelom** [comment]
I appreciate the work that has gone into this, and hopefully it will get working in the future.  Until then, I've spent way much more time than the $60 to buy an SSL cert.  I will go that route till next year.  Hopefully this will be working optimally by then.

**Comment by sjkp** [comment]
Thanks for the feedback @curelom, and good luck with buying a certificate. Until Microsoft provides any other guidance and Lets Encrypt is out of beta, that is a very valid way to solve your SSL needs. 

I have added extra logging to the latest release and increased the timeout period referred to by @chadwackerman, if you decide to try again.

**Comment by chadwackerman** [comment]
Your checkin doesn't solve the issue. You're also writing the web.config file and assuming that the server will instantly be able to respond to the new requests. There is a time period on Azure either due to restarts, or caching, or multiple instances where it does not return the files with a code 200. See my code in #36 to solve that. Again the whole architecture is a bad idea because even that won't work once you scale a server from one to two instances. This whole extension is just setting people up for pain once they grow and there's nothing warning people against it. Please consider a stronger warning on the readme or fixing this properly.

**Comment by sjkp** [comment]
@chadwackerman Didnt see that issue in my own tests but dont mind adding that fix. If you have a way to reproduce the error please let me know. In my test setup im just running an empty website could be that it is too fast so i dont experience it. 

Feel free to write a warning text that you feel are strong enough (if the beta software warning i added doesnt cut it) and i will add it to the readme and the description of the site extension. 

Thanks for your feedback yet again.

**Comment by chadwackerman** [comment]
I would add the following to the list of known issues:

- Note that Let's Encrypt works by providing automated certificates of a short (currently three month) duration. Both Let's Encrypt and this extension are BETA SOFTWARE. You will need to keep this extension updated or risk losing SSL access when your certificate expires.
- There are presently no email notifications for certificate renewal problems. You will need to check logs.
- This extension only works with single-instance web apps. If you Scale Out your web app from one to two instances, certificate renewals may fail.
- Due to rate limiting of Let's Encrypt servers, you can only request five certificates per domain name per week. Configuration errors or errors in this site extension may render you unable to retrieve a new certificate for seven days. If up-time is critical, have a plan for deploying a SSL certificate from another source in place.

**Comment by sjkp** [comment]
Thanks again @chadwackerman - I have added all the points except the one with scale out, as it should work just fine, as long as it is not multi region scale out (it at least do in my testing after your fix), and technically I don't see why it shouldn't work as all instances uses the are backed by the same storage (https://azure.microsoft.com/nb-no/documentation/articles/web-sites-available-operating-system-functionality/#_file-access-across-multiple-instances). If you have a test case where it doesn't work please let me know, in a new issue so I can fix it.
