### ISSUE TITLE
Create and enable overwrite of letsencrypt:WebAppName to work with deployment slots

### ISSUE THREAD

**Issue by vdurante** [sjkp/letsencrypt-siteextension#41]
Firs of all, thanks for this amazing extension!

I guess this extension doesn't work with deployment slots because it gets the name of the main web app to use as WebAppName. If you create and enable overwrite of the letsencrypt:WebAppName it should work with deployment slots.

**Comment by jkonecki** [comment]
+1 - I'm happy to help testing

**Comment by ComputerCowboy** [comment]
I've been looking at this also.
I have a few ideas on how to deal with this. I have figured out how to get VSO not to overwrite all my jobs on deployment. I was thinking of trying to take it a step further and run one instance of let's encrypt per resource group. It should work, might need a bit of code adjusted.

**Comment by 0xdeafcafe** [comment]
Was anything ever made of this?

**Comment by ComputerCowboy** [comment]
I haven't done anything about it yet
But I do plan to either write something or offer my code ideas to @sjkp 
For now I just added -SkipAppData to my release definition on VSO

**Comment by sjkp** [comment]
I might fix this in the upcoming weeks, since I'm going to need it for one of my apps. I will let you know. 

But in general I'm not going to be adding a lot of new features (Just bug fixes) to the site-extension, as I'm planning to make a better product that is more robust, easier to setup, and able to handle multiple sites from one interface (if people want that). Consider the rewritten version more of an Azure service, than something that sits inside your site. I also feel like I need to do this in order to make KeyVault easier to support.
