### ISSUE TITLE
Report about failed renewal

### ISSUE THREAD

**Issue by cadilhac** [sjkp/letsencrypt-siteextension#56]
Hi,

A few months back, I had setup your extension on my azure web site, following this article: https://gooroo.io/GoorooTHINK/Article/16420/Lets-Encrypt-Azure-Web-Apps-the-Free-and-Easy-Way/20047

3 months later, I received a notice from letsencrypt notifying about the expiration. I told myself the webjob should solve that. Checking today, I see that the cert has expired. All the logs for the webjob looks fine. So now I don't know where to look at to investigate. Can you help?

Thanks.

**Comment by sjkp** [comment]
Thanks for reporting this - I will take a look to see if I can reproduce it. Which version of the site extension are you running?

**Comment by cadilhac** [comment]
Right now, 0.4.15 is installed but I'm not sure which one was there when it was time to renew. I may have updated your extension after...

**Comment by sjkp** [comment]
@cadilhac did you have your site and app service plan in different resource groups? 

Because 0.4.20 fixes a bug that occured in the case, where the renewal web job would look only in the resource group hosting the app service for certificates, and would find nothing to renew in the case a different app service plan is used.

**Comment by cadilhac** [comment]
Thanks. Hopefully, it will be fixed that way.
