### ISSUE TITLE
Support for Azure AD signing key rollover?

### ISSUE THREAD

**Issue by jimmcslim** [sjkp/letsencrypt-siteextension#58]
We've received notification from Azure that our Azure AD certificates will soon be rolling over... wondering if the Let's Encrypt Site Extension currently supports automatic certificate rollover.

https://azure.microsoft.com/en-us/documentation/articles/active-directory-signing-key-rollover/?WT.mc_id=azurebg_email_Trans_1150_Azure_AD_Certificate_Rollover_EN%20ONLY

**Comment by sjkp** [comment]
The extension is not affected, as we dont use the signing keys for anything. It is also stated in the comments on the post (http://disq.us/p/1a4rzdi). 

Unfortunately the post itself is quite unclear, and it seemed like a lot of people are rightfully confused, because of the email they received. 

#57
