### ISSUE TITLE
Argument Exception when clicking Next on extension home page

### ISSUE THREAD

**Issue by nrogoff** [sjkp/letsencrypt-siteextension#93]
The following exception occurred when clicking next on the first page of the extension when no App Settings had been manually created for the App Service. Some of the App Settings were created but not all. Issue was resolved by manually populating the missing settings and continuing.

![image](https://cloud.githubusercontent.com/assets/1227639/21815489/b2567612-d754-11e6-8832-aa917ffeb0c0.png)

**Comment by sjkp** [comment]
hmm strange. I will see if I can reproduce it.

**Comment by nrogoff** [comment]
I suspect just need some exception handling or empty string/default value handling for that AppSetting?

**Comment by gvilarino** [comment]
Same here. The only thing I'm not entering is `SiteSlotName` since it's not in the documentation, and I don't know what to make of it.

![image](https://cloud.githubusercontent.com/assets/2538465/22166437/cd6b1faa-df3f-11e6-8f6b-46f9f3aca417.png)

If this refers to deployment slots, I have none (and my app is working nonetheless)

![image](https://cloud.githubusercontent.com/assets/2538465/22166458/ed7abd50-df3f-11e6-8912-cd0e88428b3f.png)

What should go there?

**Comment by gvilarino** [comment]
I just re-tried with the `prod` string, got a different error (slot not defined), then retried again with no value at all (same as 1st try) and then it went throught to the next screen :/

**Comment by sjkp** [comment]
From my investigation it is unfortunately a timing thing. On the first page it saves to app settings, which will restart the site. But it will get to the 2nd page before the restart has been initiated (probably because the scm site and the main site are not restarted simultaneously). The result is settings will be missing when it tries to read them on the second page resulting in a ugly exception. If you give it 30 sec and reload it should be fine. 

I will implement a fix. But above should be a work-around until then.

**Comment by gvilarino** [comment]
Thanks for commenting! It makes sense now.
